;;; dired-open-with-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dired-open-with.el

(autoload 'dired-open-with "dired-open-with" "\
An \\='Open with\\=' dialog for opening files in external applications.
Such dialogs are known from GUI file managers, when right-clicking a file." t)
(register-definition-prefixes "dired-open-with" '("dired-open-with--"))

;;; End of scraped data

(provide 'dired-open-with-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dired-open-with-autoloads.el ends here
