;;; cheat-sh-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cheat-sh.el

(autoload 'cheat-sh "cheat-sh" "\
Look up THING on cheat.sh and display the result.

(fn THING)" t)
(autoload 'cheat-sh-region "cheat-sh" "\
Look up the text between START and END on cheat.sh.

(fn START END)" t)
(autoload 'cheat-sh-maybe-region "cheat-sh" "\
If region is active lookup content of region, otherwise prompt." t)
(autoload 'cheat-sh-help "cheat-sh" "\
Get help on using cheat.sh." t)
(autoload 'cheat-sh-list "cheat-sh" "\
Get a list of topics available on cheat.sh.

Either gets a topic list for subject THING, or simply gets a list
of all available topics on cheat.sh if THING is supplied as an
empty string.

(fn THING)" t)
(autoload 'cheat-sh-search "cheat-sh" "\
Search for THING on cheat.sh and display the result.

(fn THING)" t)
(autoload 'cheat-sh-search-topic "cheat-sh" "\
Search TOPIC for THING on cheat.sh and display the result.

(fn TOPIC THING)" t)
(register-definition-prefixes "cheat-sh" '("cheat-sh-"))

;;; End of scraped data

(provide 'cheat-sh-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cheat-sh-autoloads.el ends here
