;;; react-snippets-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from react-snippets.el

(autoload 'react-snippets-initialize "react-snippets")
(eval-after-load 'yasnippet '(react-snippets-initialize))
(register-definition-prefixes "react-snippets" '("react-snippets-root"))

;;; End of scraped data

(provide 'react-snippets-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; react-snippets-autoloads.el ends here
