;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				evil-backward-char
				evil-delete-backward-char-and-join
				evil-forward-char
				evil-insert
				evil-normal-state
				evil-yank
				swiper
				))

(setq mc/cmds-to-run-once
      '(
				counsel-M-x
				evil-next-line
				evil-previous-line
				ivy-partial-or-done
				))
