;;; flycheck-hl-todo-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-hl-todo.el

(autoload 'flycheck-hl-todo-setup "flycheck-hl-todo" "\
Install flycheck-hl-todo, and enable it in the current buffer." t)
(register-definition-prefixes "flycheck-hl-todo" '("flycheck-hl-todo-"))

;;; End of scraped data

(provide 'flycheck-hl-todo-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-hl-todo-autoloads.el ends here
